#include <iostream>
#include <vector>
#include <algorithm>

template<typename T>
void print(const std::vector<T> & vec, const std::string & tag = "") {
    std::cout << tag << " ::\n";
    for (auto i = 0; i < vec.size(); ++i) {
        std::cout << "(" << i << ")"<< vec[i] << "\n";
    }
    std::cout << "\n";
}

struct RandomNumberGenerator {
    int maxValue;
    RandomNumberGenerator(int max_value): maxValue(max_value) 
    {}
    int operator()() {
        return rand() % maxValue;
    }
};

int main(int argc, char const *argv[])
{
    std::vector<int> v1(10);
    std::generate(v1.begin(), v1.end(), []() {
        return rand() % 100;
    });
    print(v1, "Random numbers generated by function");

    std::vector<int> v2(10);
    std::generate(v2.begin(), v2.end(), RandomNumberGenerator(1000));
    print(v2, "Random numbers generated by lambda functor");

    return 0;
}
